spring.application.name=storefront
spring.profiles.active=dev

spring.datasource.url=jdbc:mysql://localhost:3306/synergetic_storefront
spring.datasource.username=root
spring.datasource.password=Cinnamon_09

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

server.port=8080